# .github/workflows/test.yml
name: Test

on: [push, workflow_dispatch]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - run: .github/workflows/build.yml
      - run: package-lock.json
      - run: package.json
      - run: tests/test1.js
      - run: tests/test2.js
      - run: tests/test3.js
      - run: tests/test4.js
      - run: tests/test5.js
      - run: tests/test6.js
      - run: tests/test7.js
      - run: tests/test8.js
